# Generated by Django 2.0.5 on 2018-06-14 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shooter', '0003_shooter_captain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('week', models.IntegerField()),
                ('bunker_one', models.IntegerField()),
                ('bunker_two', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shooter.Season')),
            ],
        ),
    ]
