# Generated by Django 2.0.5 on 2018-06-03 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('rookie', models.BooleanField()),
                ('guest', models.BooleanField()),
                ('average', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='shooter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shooter.Shooter'),
        ),
        migrations.AddField(
            model_name='season',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shooter.Team'),
        ),
    ]
