# Generated by Django 2.0.5 on 2018-06-22 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('week', models.IntegerField(default=0)),
                ('bunker_one', models.IntegerField(default=0)),
                ('bunker_two', models.IntegerField(default=0)),
                ('average', models.FloatField(default=35.0)),
            ],
        ),
        migrations.CreateModel(
            name='Shooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('rookie', models.BooleanField(default=False)),
                ('guest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shooter.Shooter')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='shooter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shooter.Shooter'),
        ),
        migrations.AddField(
            model_name='score',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shooter.Team'),
        ),
    ]
