# Generated by Django 2.0.5 on 2018-06-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shooter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='year',
            new_name='season_year',
        ),
    ]
