# Generated by Django 2.0.5 on 2018-06-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooter', '0002_auto_20180619_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='bunker_one',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='score',
            name='bunker_two',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shooter',
            name='guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shooter',
            name='rookie',
            field=models.BooleanField(default=False),
        ),
    ]
