# Generated by Django 2.0.5 on 2018-06-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooter', '0002_auto_20180603_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='shooter',
            name='captain',
            field=models.BooleanField(default=False),
        ),
    ]
