# Generated by Django 2.0.5 on 2018-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooter', '0003_auto_20180701_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='week',
            field=models.IntegerField(choices=[('W0', 'W0'), ('W1', 'W1'), ('W2', 'W2'), ('W3', 'W3'), ('W4', 'W4'), ('W5', 'W5'), ('W6', 'W6'), ('W7', 'W7'), ('W8', 'W8'), ('W9', 'W9'), ('W10', 'W10'), ('W11', 'W11'), ('W12', 'W12'), ('W13', 'W13'), ('W14', 'W14'), ('W15', 'W15')]),
        ),
    ]
