# Generated by Django 2.0.5 on 2018-06-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooter', '0003_shooter_captain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('week', models.IntegerField()),
                ('bunker_one', models.IntegerField()),
                ('bunker_two', models.IntegerField()),
            ],
        ),
    ]
