# Generated by Django 2.0.5 on 2018-06-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooter', '0004_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateField(),
        ),
    ]
