# Generated by Django 2.0.5 on 2018-06-19 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shooter', '0005_auto_20180618_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='score',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='shooter.Score'),
            preserve_default=False,
        ),
    ]
