# Generated by Django 2.1.7 on 2019-02-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooter', '0006_auto_20180708_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='average',
        ),
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='team',
            name='season',
        ),
        migrations.AddField(
            model_name='shooter',
            name='captain',
            field=models.BooleanField(default=False),
        ),
    ]
